# Assignment For Numpy
Difficulty Level Beginner

# Import the numpy package under the name np

In [7]:
import numpy as np

# Create a null vector of size 10

In [6]:
import numpy as np
x=np.zeros(10)
print (x)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Create a vector with values ranging from 10 to 49

In [9]:
import numpy as np
x = np.arange(10, 49)
print(x)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


# Find the shape of previous array in question 3

In [14]:
import numpy as np
x= np.arange(10,49)
print(x.shape)

(39,)


# Print the type of the previous array in question 3

In [15]:
import numpy as np
x= np.arange(10,49)
x.dtype

dtype('int32')

# Print the numpy version and the configuration

In [48]:
import numpy as np
print(np.__version__)

print(np.show_config())


1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


# Print the dimension of the array in question 3

In [19]:
import numpy as np
x= np.arange(10, 49)
x.ndim

1

# Create a boolean array with all the True values

In [21]:
import numpy as np
bool_arr = np.ones(10, dtype=bool)
print('Numpy Array: ')
print(bool_arr)

Numpy Array: 
[ True  True  True  True  True  True  True  True  True  True]


# Create a two dimensional array

In [25]:
import numpy as np
x= np.array([[1,2,3],[1,2,3]])
print(x)

[[1 2 3]
 [1 2 3]]


# Create a three dimensional array

In [26]:
import numpy as np
x=np.array([[1,2,3],[1,2,3],[1,2,3]])
print(x)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


# Difficulty Level Easy

# Reverse a vector (first element becomes last)

In [27]:
import numpy as np
import numpy as np
x = np.arange(12, 38)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)


Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


# Create a null vector of size 10 but the fifth value which is 1

In [29]:
import numpy as np
x=np.zeros(10)
x[4]=1
print (x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Create a 3x3 identity matrix

In [30]:
import numpy as np
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# arr = np.array([1, 2, 3, 4, 5])
Convert the data type of the given array from int to float

In [32]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)
x=x.astype('float64')
print(x)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


# arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
Multiply arr1 with arr2

In [34]:

import numpy as np

arr1 = np.array([[1.,2.,3.],[4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],
                 [7.,2.,12.]])

arr_result = np.multiply(arr1, arr2)

print(arr_result)

[[ 0.  8.  3.]
 [28. 10. 72.]]


# arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
Make an array by comparing both the arrays provided above

In [35]:
import numpy as np 
  
an_array = np.array([[1.,2.,3.],[4.,5.,6.]])
another_array = np.array([[0.,4.,1.],
                 [7.,2.,12.]])
  
comparison = an_array == another_array 
equal_arrays = comparison.all() 
  
print(equal_arrays) 

False


# Extract all odd numbers from arr with values(0-9)

In [46]:
import numpy as np
a = np.array([0,1,2,3,4,5,6,6,7,7,8,9])
a[a % 2 == 1]

array([1, 3, 5, 7, 7, 9])

# Replace all odd numbers to -1 from previous array

In [43]:
import numpy as np 
 
 
v1 = np.array([1,2,3,4,5,6,7,8,9])  
 
v1[v1%2==1] = -1            
 
 
print (v1) 

[-1  2 -1  4 -1  6 -1  8 -1]


# arr = np.arange(10)
Replace the values of indexes 5,6,7 and 8 to 12

In [4]:
import numpy as np
arr=np.arange(10)
arr[5]=12
arr[6]=12
arr[7]=12
arr[8]=12
print (arr)


[ 0  1  2  3  4 12 12 12 12  9]


# Create a 2d array with 1 on the border and 0 inside

In [5]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Difficulty Level Medium

# arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
Replace the value 5 to 12

In [6]:
import numpy as np
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[1][1]=12
print (arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


# arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
Convert all the values of 1st array to 64

In [10]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0]=64
print (arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [52]:
import numpy as np
x= np.array([[0,1,2,3,4],[5,6,7,8,9]])
y=x[0]
print(y)




[0 1 2 3 4]


# Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [53]:
import numpy as np
x= np.array([[0,1,2,3,4],[5,6,7,8,9]])
y=x[1]
z=y[1]
print(z)


6


# Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [58]:
import numpy as np
arr2d=np.array([[0,1],[2,3],[4,5],[6,7],[8,9]])
x=arr2d[0][1]
print(x)

1


# Create a 10x10 array with random values and find the minimum and maximum values

In [31]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.67977136 0.48243563 0.92166008 0.92564495 0.84472924 0.19718881
  0.33194737 0.85995016 0.77405843 0.81389669]
 [0.99559067 0.3084972  0.31308305 0.63071554 0.91641219 0.55726004
  0.78384012 0.58929839 0.25177725 0.74545551]
 [0.35891952 0.28987301 0.87256176 0.2688762  0.60618768 0.96837859
  0.83037702 0.2152547  0.66287027 0.93803374]
 [0.85928963 0.42865463 0.28962329 0.68496447 0.52786598 0.16459264
  0.58025493 0.13751009 0.35550391 0.76422158]
 [0.60212935 0.4261072  0.59933247 0.10560663 0.83373322 0.12100176
  0.9665733  0.78030282 0.26241366 0.4109152 ]
 [0.6590607  0.65364916 0.53375269 0.25952344 0.25942745 0.30802122
  0.72106416 0.60007141 0.0628347  0.19460337]
 [0.05206437 0.30883523 0.2584638  0.51828128 0.34841221 0.92432036
  0.50718546 0.86918363 0.31882457 0.50844065]
 [0.38382479 0.82974537 0.22638825 0.31085674 0.7427246  0.29735392
  0.8058008  0.49605212 0.18041365 0.12173706]
 [0.26763235 0.69130938 0.12482569 0.00846901 0.52910243 0.09055

# 27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the common items between a and b

In [36]:

import numpy as np  
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Original arrays", a, ' ', b)  
c = np.intersect1d(a, b) 
print("Common values", c) 

Original arrays [1 2 3 2 3 4 3 4 5 6]   [ 7  2 10  2  7  4  9  4  9  8]
Common values [2 4]


# a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the positions where elements of a and b match

In [68]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
x = np.where(a ==b)
print(x[0])

[1 3 5 7]


# names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will

In [9]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])   
data = np.random.randn(7, 4)
print(names!='Will')
print(data[names!='Will'])


[ True  True False  True False  True  True]
[[-0.38291557 -0.26940882  1.12623088  2.14690249]
 [-1.01473938 -1.01913979 -0.35624163  0.30972201]
 [ 0.86466064 -0.34526947  1.31398845  2.68087249]
 [-0.73292617 -0.99513772  0.62485904 -0.03188279]
 [ 0.92595615  0.18340155  2.28170899  0.83167829]]


# names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will and Joe

In [20]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])   
data = np.random.randn(7, 4)
b=(names!='Will') & (names!='Joe')
print(b)
print(data[b])


[ True False False  True False False False]
[[ 0.70931018 -0.40019489  0.60973733  0.20211472]
 [ 0.11599106 -1.05575398 -0.16655558 -1.21264123]]


# Difficulty Level Hard

Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [71]:
import numpy as np
arr = np.arange(9).reshape(3,3)
rand_arr = np.random.uniform(1,15, size=(5,3))
print(rand_arr)

[[12.17458669  1.76946315  9.48016269]
 [11.29765603  7.73028327  3.72941879]
 [ 9.68066146  6.51628444 14.76354635]
 [ 8.44819435  7.3729271   5.90184405]
 [ 5.49709369  6.28775574  8.41267197]]


# Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [29]:
import numpy as np
x=np.arange(1.,17.).reshape(2,2,4)
print(x)


[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


# Swap axes of the array you created in Question 32

In [33]:
import numpy as np
x=np.arange(1.,17.).reshape(2,2,4)
y=x.swapaxes(2,1)
print(y)

[[[ 1.  5.]
  [ 2.  6.]
  [ 3.  7.]
  [ 4.  8.]]

 [[ 9. 13.]
  [10. 14.]
  [11. 15.]
  [12. 16.]]]


# Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [46]:
import numpy as np
x=np.array([1,0.2,2,3,7,1,16,5,8,1])
c=np.sqrt(x) 
np.where((np.sqrt(x)<0.5),0,c)


array([1.        , 0.        , 1.41421356, 1.73205081, 2.64575131,
       1.        , 4.        , 2.23606798, 2.82842712, 1.        ])

# Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [6]:
import numpy as np
a=np.array([9,7,5,8,3,2])
b=np.array([2,6,3,8,5,7])
print("Original Array:")
print(a,b) 
amax = a.max()
bmax = b.max()
print("Maximum Values:")
print(amax)
print(bmax)

Original Array:
[9 7 5 8 3 2] [2 6 3 8 5 7]
Maximum Values:
9
8


# names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
Find the unique names and sort them out!

In [3]:
import numpy as np
array = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
ar=np.unique(array)
print("unique values :",ar)
b=np.sort(ar)
print(b)

unique values : ['Bob' 'Joe' 'Will']
['Bob' 'Joe' 'Will']


# a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])
From array a remove all items present in array b

In [48]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
result=np.setdiff1d(a,b)
print(result)


[1 2 3 4]


# Following is the input NumPy array delete column two and insert following new column in its place.
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = numpy.array([[10,10,10]])

In [66]:
import numpy as np
sampleArray=np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
x=np.delete(sampleArray,1,1)
print(np.insert(x,1,newColumn,1))



[[34 10 73]
 [82 10 12]
 [53 10 66]]


# x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])
Find the dot product of the above two matrix

In [52]:
import numpy as np
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
d= x.dot(y)
print(d)

[[ 28.  64.]
 [ 67. 181.]]


# Generate a matrix of 20 random values and find its cumulative sum

In [72]:
import numpy as np
x=np.random.rand(4,5)
print(x.cumsum())

[ 0.99812628  1.20586312  1.57405444  1.65467948  2.25548099  3.12086263
  4.07455431  4.41557428  5.0778741   6.0293368   6.33456311  6.81317043
  7.06038066  7.65812186  8.16014521  8.20027535  8.52837773  9.11146829
  9.94353403 10.8675923 ]
